sudo: required
services: 
  - docker

before_install:
  - docker build -t heba/docker-react -f Dockerfile.dev .

# script:
#  - docker run heba/docker-react npm run test -- -- coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-676946728267"
  bucket_path: "Dockerreact-env"
  on:
    branch: main
  
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"